steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "`ls ./dataflow/`"
    wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tar.xz
    tar -xvzf Python-3.8.0.tar.xz
    bash ./Python-3.8.0/install-sh
    python3 -m pip install -r requirements.txt
    python3 ./dataflow/RecordToBigQuery.py \
    --input gs://cb-dataflow-storage/test-file.csv \
    --output-main cb-dataflow-python:ADataset_Staging.ATest \
    --output-reject cb-dataflow-python:Common.Reject \
    --runner DataflowRunner \
    --project cb-dataflow-python \
    --temp_location gs://cb-dataflow-storage/temp/ \
    --staging_location gs://cb-dataflow-storage/staging/ \
    --extra-package /Users/karthikeysurineni/dataflow-python/dataflow/BQUtil.py
  env:
  - 'PROJECT=$PROJECT_ID'
substitutions: